is_physics_informed: True
save_path:  'trained_models/planet_slim_mlp_1/'
dataset_path: data/iter_like_data.h5 # planet/tests/data/iter_like_data_sample.h5 #data/iter_like_data.h5
do_super_resolution: false
batch_size: 256
epochs: 2000
model_name: planet_slim_mlp
log_to_wandb: True
wandb_project: planet
save_checkpoints: true
resume_from_checkpoint: false
num_workers: 0
planet_config:
  hidden_dim: 128
  nr: 64
  nz: 64
  n_measures: 302