is_physics_informed: True
save_path:  'trained_models/test/'
dataset_path: data/iter_like_data.h5
do_super_resolution: false
batch_size: 256
epochs: 1500
model_name: planet_slim
log_to_wandb: true
wandb_project: planet_test
save_checkpoints: true
resume_from_checkpoint: false
num_workers: 0
planet_config:
  hidden_dim: 128
  nr: 64
  nz: 64
  branch_in_dim: 302